### PR TITLE
Adds function for creating a page from a string.

### PR DESCRIPTION
**Pull request by jakemcc**
This adds a function for creating a HtmlPage from a string. This is particularly useful when testing code that uses yokogiri.

### CODE REVIEW

**Comment by devn** [comment]
Howdy Jake!

Can `http://fakeurl.com` be `file://fake`? If it absolutely has to be a real URL I'd prefer it to point at `http://example.com` since `fakeurl.com` is owned by a squatter.

**Comment by jakemcc** [comment]
Seems like it.

**Comment by devn** [comment]
Cool, last two nitpicks and then I'll merge:

1.) Please make `file://fakeurl.com` => `file://fake-response-url`
2.) Could you use `(io/as-url "file://fake-response-url")` instead of `(java.net.URL. ...)`?

Both are minor, but I'm already using `io/as-url` in `as-page`. Maybe the right thing to do would be to support a string AND a file in `as-page`. Whaddya think?

**Comment by jakemcc** [comment]
I lean towards having separate functions. Prefer having a function that operates on a single thing.

**Comment by jakemcc** [comment]
Any chance of releasing a version with this pull request included?

**Comment by devn** [comment]
Oh, duh. Yes.  

Sorry about that. I'll push a release for you in a minute. In the middle of something at the moment.

**Comment by devn** [comment]
Well, wouldn't you know it. I spaced on getting a deploy out for you. Sorry about that.

1.5.8 is now on Clojars.

:cake:

**Pull request merged**
